// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClockController from "./clock_controller"
application.register("clock", ClockController)

import CountdownTimer2Controller from "./countdown_timer_2_controller"
application.register("countdown-timer-2", CountdownTimer2Controller)

import CountdownTimerController from "./countdown_timer_controller"
application.register("countdown-timer", CountdownTimerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
