// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClockController from "./clock_controller"
application.register("clock", ClockController)

import CountdownTimerController from "./countdown_timer_controller"
application.register("countdown-timer", CountdownTimerController)

import MyTimerController from "./my_timer_controller"
application.register("my-timer", MyTimerController)

import PomodoroController from "./pomodoro_controller"
application.register("pomodoro", PomodoroController)

import SessionTimerController from "./session_timer_controller"
application.register("session-timer", SessionTimerController)

import StudySessionController from "./study_session_controller"
application.register("study-session", StudySessionController)

import StudySessionEndController from "./study_session_end_controller"
application.register("study-session-end", StudySessionEndController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import XpController from "./xp_controller"
application.register("xp", XpController)
