// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClockController from "./clock_controller"
application.register("clock", ClockController)

import FlipdownController from "./flipdown_controller"
application.register("flipdown", FlipdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
